version: '3.0'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: backend:v3.0
    container_name: backend
    restart: always
    volumes:
      - "C:/Users/Professional/Desktop:/app"
    networks:
      sep_network:
        ipv4_address: 172.28.0.2
  
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: frontend:v3.0
    container_name: frontend
    restart: always
    ports:
      - "8070:8070"
    depends_on:
      - backend
    networks:
      sep_network:
        ipv4_address: 172.28.0.3
  
networks:
    sep_network:
      driver: bridge
      ipam:
        config:
          - subnet: 172.28.0.0/16